//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int id { get; set; }
        public string card_number { get; set; }
        public Nullable<System.DateTime> expiration { get; set; }
        public int cvv { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string company { get; set; }
        public Nullable<int> id_account { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
